# Files or directories to exclude

ignore = [
    "*.ipynb",
    ".git",
    "venv",
    "build",
    "dist",
    "__pycache__",
    ".env",
    "llm_blocks.egg-info",
    ".gitignore",
    "setup.py",
    "README.md",
    "requirements.txt",
    "turbo_docs.toml",
]